version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcher-app
    volumes:
      - ./:/var/www
  db:
    image: mysql:latest
    container_name: watcher-db
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: C.UTF-8
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    depends_on:
      - app